language: python
python: 3.6
branches:
  only:
  - master
  - ci
  - "/^(release\\/)?v([1-9]\\d*!)?(0|[1-9]\\d*)(\\.(0|[1-9]\\d*))*((a|b|rc)(0|[1-9]\\d*))?(\\.post(0|[1-9]\\d*))?(\\.dev(0|[1-9]\\d*))?$/"
before_install:
- pip install -r requirements-ci.txt
install: pip install -e .
script: make cover
after_success: coveralls
deploy:
  provider: pypi
  skip_cleanup: true
  user: babakhani
  password:
    secure: jYVECYen2qd+Vii1TSfxwhGLnIem5E4qv60k9qCs+08UHzvAx45kkTtWqwUgiw6+i5aV6mAhwyE5/q+qFkuIISjENXzi8BKa0DHGjwhL1BG8CJwy6JyPfobCdSX+VILS31fP2iJD2NCX8WLV4oZMHupW4zjyOXZnPsKdsFIE69HDJYhugr6DC5Flvlxwuin9LNFysU3Omwpd+7njG2z3eY5cnffsb7nmOneV9+MJxNIAcDmxYC9Xvg/hVnR1rxnzpx6He5Bt8mN0k+NWEnSqk7ejQSE4ByvHoqZ8XiyKZsCBlkQteybNpXNEHKOK7xRVYEaDR5dHC8KUjNFCCJXSVB/XeMnLXXy9cLPxLfhR8awKZXswh9l2noCLB1NewU96+l4Mk51mEbIemfFGUPsH8JP+OFCqfcLybIlB3bpqlqnrApbOnXpqaWpkeZUJSUgDvYKy1jnioSO0t7TPMrrux0xaM89DZi0EXbV6H5q3UZoffK6Bn03Nt6ruIOpTqEBNYPX8U/xgy0Xh1FLEGUhy4/yW7wpUrXHB+5NfCRmdfNTxGxFtesx8TTfl23Y55LGIqb4CyIPokTGfNVfEV5vbgD50N90CEUSRWFjor9XT5Q9KgzAagql/lW2K544iJTPyW9ZYtLItF5n05wsBeCoAqCAJvIqZLpd0VuA/Lv22MBk=
  on:
    tags: true
    distributions: sdist
    repo: babakhani/markdownserver
    condition: "$TRAVIS_PYTHON_VERSION = 3.6"
