language: python
python: 3.6
branches:
  only:
  - master
  - ci
  - "/^(release\\/)?v([1-9]\\d*!)?(0|[1-9]\\d*)(\\.(0|[1-9]\\d*))*((a|b|rc)(0|[1-9]\\d*))?(\\.post(0|[1-9]\\d*))?(\\.dev(0|[1-9]\\d*))?$/"
before_install:
- pip install -r requirements-ci.txt
install: pip install -e .
script: make cover
after_success: coveralls
deploy:
  provider: pypi
  skip_cleanup: true
  user: __token__
  password:
    secure: csqvkGlT/z6mJ3IuuaC721GDuYqI0Dt16hWcf7E0s3bOCOpYCwNHofgSe7RnexsTL0rCMjjl4IixcIl0KSkd9uCYjEcTG2FbFlY98CTTOkVmCyaHdJcYU+NSmh31klD4f663eHm+fWdpSB5jXSeo1us9AokQc8VGRRm1rk9dLjkr8Ksb9ifPCN7doPUp5ScTZjP2xZoPjPDZ1I8Yu0UPiRwbdI+aGpItUdUENjD567VGilClzE4/LXsU/QKUDjKmNJCvyMxli+DDD0AbpBuqfgrgcDkF4+bsniKcyA7P6+xpiNH/IdtgAZXi0k2NcMds1oRgSFtGwQeZDTgTsPVv0z+Rkut83nTF/NEt80X5qvB2cqC7PHcOZnDnaLHXy2Xg+uvhRyakaqEcglvw0sRfufGOYftc8q47kymNA2e6DDamYdVxViVkAdpbojuwk1Xa2JmxtfG/87/GtAdbjtTYbTjGVjdRvfwQNChLmnU7jf5wFqxm/L/qRyVe86AiMl1oKHY01mo76P1MknKg1/Z/A4u/z5+Gu8hyRyOZZXW5ua6OXblpVgDIRuGdUz4J/wl/bjvwVXN5KzTsCk3PCdVtuHEa9pb8d3PGV/g/wouP/EKZ03rt9xqi8Tsv3Fs+Yu5lZoEsfK6CmqIgw9gEoQqeHmdzMEe8EfEOSli1GohMBcU=
  on:
    tags: true
    distributions: sdist
    repo: babakhani/markdownserver
    condition: "$TRAVIS_PYTHON_VERSION = 3.6"
